### ISSUE TITLE
Player does not fall when walking sideways off a ladder

### ISSUE THREAD

**Issue by eddivita** [mrbwaters/fire_drill#17]

**Comment by jbussing** [comment]
@mrbwaters I don't think we want this behavior but I did leave this within scr_player_climb() on line 26-27 if we want to have this be a thing https://github.com/mrbwaters/fire_drill/pull/18

**Comment by mrbwaters** [comment]
Per @jbussing, this is a feature.

I asked Joe to tighten up ladder behaviors so that they are more aligned with Mega Man: You need a key press to get onto a ladder, you can only jump (not run) off unless you're at the top or bottom.

You can see these changes documented in Joe's FSM presentation. Let me know if you have conviction that we should not go this way.

Relatedly: When we have character animation, we'll likely want to to lock in the ladder climbing so that you only climb in the middle. That might involve narrowing the collision mask of the ladder objects so that the sprite doesn't jump from the edge of the ladder to the center.

**Comment by jbussing** [comment]
On your last point, you don't want the character hanging from the side of a ladder. So the fix to that should involve tightening or shrinking the ladder object collision as you suggest which would get the player more to the middle of the ladder sprite rather than hanging off the edge. Alternatively, we can also re-adjust the player position once on the ladder to the middle of the sprite. This way when approaching the top the player can fit through the opening.

We may want to do one or both of these things.

**Comment by eddivita** [comment]
Similarly, I was thinking we might want to shrink the width of the player collider by 1 pixel each side to make sure player falls through gaps.  I noticed the player doesn't always fall when walking across a 1-cell wide gap.

Can solve the player position issue by moving player a few pixels towards center of ladder each step while in climb state.  Don't jump them to center all at once, do it over a few steps.

**Comment by mrbwaters** [comment]
Agreed! I think having proper character art will also help with this. Mike isn't responding to my messages though :/

I recommend y'all [check out how ladders work in Mega Man 2](https://www.retrogames.cz/play_346-NES.php?language=EN). The first room of Crash Man's stage has ladders to try. Here there is no horizontal drift on ladders at all and your character just quickly shifts a little when you go into climbing. I actually think it looks pretty good and have played the game for 30 years and never been bothered by it.

**Comment by jbussing** [comment]
I love this @eddivita! 

Idle, Run, and Fall state functions currently have checks with the ladder object to transition to Climb, but i also think Jump should have the same logic for example can a player jump on the upward movement and catch a ladder before the fall state is triggered.

And as far as the code to re-center the sprite that should live in the Climb state function.

@eddivita feel free to run with this, I just wanted to call out the affected states for awareness, although you probably already knew that 😉

**Comment by eddivita** [comment]
Just did a small update to main with the nudge to center of ladder.

Is it ok to push to main for small revisions like this, or should we always use a branch + pull request?

**Comment by mrbwaters** [comment]
I think small commits to main are okay but we should try to avoid them if possible.

Ideally we'd make those adjustments to the big branch shift before we merge it.

Sent via Superhuman ( ***@***.*** )
